{
  "comments": [
    {
      "key": {
        "uuid": "6ad620dd_d108c4f7",
        "filename": "subcmds/upload.py",
        "patchSetId": 5
      },
      "lineNbr": 256,
      "author": {
        "id": 1006257
      },
      "writtenOn": "2014-05-06T18:19:18Z",
      "side": 1,
      "message": "Is this necessary though?  Would anything bad happen if we encode to utf-8?  Also, it looks like this exists to make sure that we aren\u0027t using utf-16 or something else, in which case we would definitely want to keep this even in python3.",
      "revId": "2d67f6bd4f0ba004709971cc120ab845bc13f6a7",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "0aae8465_86020ad4",
        "filename": "subcmds/upload.py",
        "patchSetId": 5
      },
      "lineNbr": 256,
      "author": {
        "id": 1016072
      },
      "writtenOn": "2014-05-06T18:47:18Z",
      "side": 1,
      "message": "the issue is Python2 can\u0027t encode everything, so you\u0027re risking getting Decode Errors\n\n\u0027Ä…\u0027.encode(\u0027utf-8\u0027) results in a UnicodeDecodeError\n\nThis takes us back to the original commit of defining unicode as str, and letting the encode run it\u0027s own course",
      "parentUuid": "6ad620dd_d108c4f7",
      "revId": "2d67f6bd4f0ba004709971cc120ab845bc13f6a7",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": false
    }
  ]
}