{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "27aed050_6640b8eb",
        "filename": "/COMMIT_MSG",
        "patchSetId": 3
      },
      "lineNbr": 11,
      "author": {
        "id": 1007145
      },
      "writtenOn": "2022-05-10T14:44:58Z",
      "side": 1,
      "message": "is this because you\u0027re using an old repo launcher ?  if you\u0027re using the latest launcher, it should have shown an error to you directly and never imported this code.  what does `repo version` say ?",
      "revId": "9866252cf6b343984607a1e876c915fdc9ece8d0",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "2786aef7_5f7975f3",
        "filename": "/COMMIT_MSG",
        "patchSetId": 3
      },
      "lineNbr": 11,
      "author": {
        "id": 1148165
      },
      "writtenOn": "2022-05-10T16:49:53Z",
      "side": 1,
      "message": "\u003crepo not installed\u003e\nrepo launcher version 2.21\n       (from /usr/bin/repo)\ngit 2.7.4\nPython 3.5.2 (default, Jul 17 2020, 14:04:10) \n[GCC 5.4.0 20160609]\nOS Linux 5.13.0-40-generic (#45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022)\nCPU x86_64 (x86_64)\nBug reports: https://bugs.chromium.org/p/gerrit/issues/entry?template\u003dRepo+tool+issue\n\n\ndirectly download from https://storage.googleapis.com/git-repo-downloads/repo",
      "parentUuid": "27aed050_6640b8eb",
      "revId": "9866252cf6b343984607a1e876c915fdc9ece8d0",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "746d1955_16e5cf99",
        "filename": "/COMMIT_MSG",
        "patchSetId": 3
      },
      "lineNbr": 11,
      "author": {
        "id": 1007145
      },
      "writtenOn": "2022-05-13T05:21:01Z",
      "side": 1,
      "message": "that implies something is not working.  the repo launcher should have rejected your Python 3.5 usage itself.  that\u0027s the point of the requirements.json file that the repo launcher inspects.\n\nwhile your CL here probably improves things with the current versions, i don\u0027t think it\u0027ll help when/if we start using f-strings in main.py itself.  that is why the requirements.json logic was added.\n\nwe might still merge this CL to help in the short term (i haven\u0027t made up my mind about it), but it\u0027s def not the long term answer, and once we do start using things like f-string in main.py, we\u0027ll revert this CL since it no longer helps.\n\ndo you want to take a look now to see why requirements.json parsing in the repo launcher isn\u0027t working ?",
      "parentUuid": "2786aef7_5f7975f3",
      "revId": "9866252cf6b343984607a1e876c915fdc9ece8d0",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "de86e833_747df562",
        "filename": "/COMMIT_MSG",
        "patchSetId": 3
      },
      "lineNbr": 11,
      "author": {
        "id": 1148165
      },
      "writtenOn": "2022-05-18T09:28:23Z",
      "side": 1,
      "message": "Well. Google official document will download repo 2.21 by default. and v2.21 allow python3.5\nSo i don\u0027t understand why \"repo launcher should have reject python3.5\". Where does it come from?",
      "parentUuid": "746d1955_16e5cf99",
      "revId": "9866252cf6b343984607a1e876c915fdc9ece8d0",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "4ef498d4_e6cb951c",
        "filename": "/COMMIT_MSG",
        "patchSetId": 3
      },
      "lineNbr": 11,
      "author": {
        "id": 1007145
      },
      "writtenOn": "2022-05-18T13:26:05Z",
      "side": 1,
      "message": "please see the requirements.json file.  it has an explanation in it.",
      "parentUuid": "de86e833_747df562",
      "revId": "9866252cf6b343984607a1e876c915fdc9ece8d0",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "7d4a4ab9_9ca6380d",
        "filename": "/COMMIT_MSG",
        "patchSetId": 3
      },
      "lineNbr": 11,
      "author": {
        "id": 1148165
      },
      "writtenOn": "2022-05-18T15:53:03Z",
      "side": 1,
      "message": "I already read it. But i\u0027m totally confused where am i wrong. Maybe it\u0027s not the correct fix. But the problem exists. Here is the thing\n---------------------------------------------------------------------------\nProblem: repo won\u0027t prompt correct error or warning on OS which only has python3.5 (e.g. Ubuntu 16.04)\n--------------------------------------------------------------------------\nExpect: repo will tell me python3.5 is out of date and require at least python3.5\n-----------------------------------------------------------------------\nWhat i got: \n\u0027\u0027\u0027\n$ repo init\nDownloading Repo source from https://gerrit.googlesource.com/git-repo\nrepo: Updating release signing keys to keyset ver 2.3\nTraceback (most recent call last):\n  File \"/tmp/1/.repo/repo/main.py\", line 42, in \u003cmodule\u003e\n    from git_config import RepoConfig\n  File \"/tmp/1/.repo/repo/git_config.py\", line 774\n    self._Set(f\u0027superproject.{key}\u0027, value)\n                                  ^\nSyntaxError: invalid syntax\n\u0027\u0027\u0027\n---------------------------------------------------------------------\nStep to reproduct:\n1. install a pure Ubuntu 16.04\n2. \u0027curl -o /usr/bin/repo https://storage.googleapis.com/git-repo-downloads/repo\u0027\\\n3. repo init\n4 Get \u0027invalid syntax\u0027 error rather than \"your python is too old\"",
      "parentUuid": "4ef498d4_e6cb951c",
      "revId": "9866252cf6b343984607a1e876c915fdc9ece8d0",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "5705da70_1562710e",
        "filename": "main.py",
        "patchSetId": 3
      },
      "lineNbr": 23,
      "author": {
        "id": 1007145
      },
      "writtenOn": "2022-05-10T14:44:58Z",
      "side": 1,
      "message": "incorrect style.  see the comment block below for the right style.",
      "revId": "9866252cf6b343984607a1e876c915fdc9ece8d0",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "16160504_f3f4e41a",
        "filename": "main.py",
        "patchSetId": 3
      },
      "lineNbr": 23,
      "author": {
        "id": 1148165
      },
      "writtenOn": "2022-05-11T02:31:34Z",
      "side": 1,
      "message": "Ack",
      "parentUuid": "5705da70_1562710e",
      "revId": "9866252cf6b343984607a1e876c915fdc9ece8d0",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    }
  ]
}