{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "929595ba_27131c45",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1167921
      },
      "writtenOn": "2023-10-17T16:25:13Z",
      "side": 1,
      "message": "The reason the tests are failing is because during test setup, the wrapper is used to create a new \"remote\", including committing new changes, which requires a working directory (https://gerrit.googlesource.com/git-repo/+/refs/heads/main/tests/test_wrapper.py#478). Probably the issue can be fixed by simply bypassing the wrapper behavior for setup.",
      "revId": "c7ca77e823216c987adfa948317098dff0bbdfc6",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    }
  ]
}